"""Reference pages: generation, discovery and crawl hygiene.

One pass, replacing postbuild_index.py and postbuild_herbs.py.

Chart data no longer lives in this file. Each chart is a module in
charts/ exposing SLUG and PAGE, and discover() picks them up at runtime.
That was the remaining structural problem: this module had become the
place new charts were appended, so every addition meant rewriting 20KB of
working code to add a dict. Now a chart is a new file and nothing here
changes.

What this pass does, in order:

  1. Discovers charts/*.py and registers each PAGE into
     reference_content.PAGES so the existing renderers can see them.
  2. Writes a page for each discovered chart, cloning a live reference
     page as the HTML shell so header, footer, stylesheet links and font
     preloads stay identical with no markup duplicated here.
  3. Adds a card for every reference page to the kitchen notes grid, using
     the real kn-guide-card markup so the cards inherit existing styles.
  4. Corrects the library eyebrow, which claimed three techniques above a
     grid that has since grown well past that.
  5. Repairs robots.txt: generated directives were indented, which makes
     crawlers read none of them, and the sitemap line was relative when it
     must be absolute.
  6. Appends sitemap entries for any reference page missing from it.

Scope note: postbuild.py still owns the recipe-side transforms and the
first three reference pages. Both passes belong in build.py once the
structure stops moving.

Run locally with:
    python build.py && python postbuild.py && python postbuild_reference.py
"""
import importlib.util
import json
import re
import sys
from html import escape as esc
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'
CHARTS = ROOT / 'charts'

# Any live reference page works as the HTML shell. This one is generated by
# postbuild.py, so it exists before this pass runs.
SHELL_SOURCE = 'can-to-cup-conversions'

# Single marker for idempotency across all reference cards.
CARD_MARKER = 'data-reference-card'


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def load_charts():
    """Import every chart module in charts/ and return {slug: PAGE}.

    Loaded by file path rather than package import so the directory needs
    no entry in sys.path and a broken chart cannot take down the others.
    """
    found = {}
    if not CHARTS.exists():
        return found

    for path in sorted(CHARTS.glob('*.py')):
        if path.name.startswith('_'):
            continue
        try:
            spec = importlib.util.spec_from_file_location(
                f'charts.{path.stem}', path
            )
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
        except Exception as exc:
            print(f'  warn: {path.name} failed to load ({exc})')
            continue

        slug = getattr(module, 'SLUG', None)
        page = getattr(module, 'PAGE', None)
        if not slug or not isinstance(page, dict):
            print(f'  warn: {path.name} has no SLUG/PAGE, skipped')
            continue

        found[slug] = page

    return found


def register(charts):
    """Merge discovered charts into reference_content.PAGES.

    Returns the module, or None if it cannot be imported. Registering makes
    the existing body() and article_jsonld() renderers work on the charts
    without duplicating any rendering code here.
    """
    try:
        import reference_content as rc
    except Exception as exc:
        print(f'  skip: reference_content not importable ({exc})')
        return None

    for slug, data in charts.items():
        rc.PAGES[slug] = data
    return rc


# ---------------------------------------------------------------------------
# Page generation
# ---------------------------------------------------------------------------

def write_page(rc, slug):
    """Write one reference page, cloning a live page as the shell."""
    shell_path = DIST / 'kitchen-notes' / SHELL_SOURCE / 'index.html'
    if not shell_path.exists():
        print(f'  skip {slug}: shell page not found')
        return False

    data = rc.PAGES[slug]
    html = shell_path.read_text(encoding='utf-8')

    html = re.sub(
        r'<title>.*?</title>',
        f'<title>{esc(data["title"])} \u2014 Bored of Toast</title>',
        html, count=1, flags=re.S,
    )

    description = esc(data['description'], quote=True)
    title_attr = esc(data['title'], quote=True)

    html = re.sub(
        r'(<meta name="description" content=")[^"]*(")',
        lambda m: m.group(1) + description + m.group(2),
        html, count=1,
    )

    for prop in ('og:title', 'twitter:title'):
        html = re.sub(
            r'(<meta (?:property|name)="' + prop + r'" content=")[^"]*(")',
            lambda m: m.group(1) + title_attr + m.group(2),
            html, count=1,
        )

    for prop in ('og:description', 'twitter:description'):
        html = re.sub(
            r'(<meta (?:property|name)="' + prop + r'" content=")[^"]*(")',
            lambda m: m.group(1) + description + m.group(2),
            html, count=1,
        )

    # Canonical, og:url and any other self-references.
    html = html.replace(
        f'/kitchen-notes/{SHELL_SOURCE}/',
        f'/kitchen-notes/{slug}/',
    )

    body_html = rc.body(slug)
    html, count = re.subn(
        r'(<main[^>]*>)(.*?)(</main>)',
        lambda m: m.group(1) + body_html + m.group(3),
        html, count=1, flags=re.S,
    )
    if count == 0:
        print(f'  warn {slug}: <main> not found, page not written')
        return False

    schema = json.dumps(rc.article_jsonld(slug), ensure_ascii=False)
    html = re.sub(
        r'(<script type="application/ld\+json">)(.*?)(</script>)',
        lambda m: m.group(1) + schema + m.group(3),
        html, count=1, flags=re.S,
    )

    out_dir = DIST / 'kitchen-notes' / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / 'index.html').write_text(html, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------
# Listing cards
# ---------------------------------------------------------------------------

def build_cards(rc):
    """Cards for every reference page, in the existing card shape.

    reference_content defines its own index_cards(), but against class names
    that were never added to the stylesheet. Rendering against the real
    kn-guide-card markup means the cards inherit every existing style,
    including hover and focus states, with no CSS added.
    """
    cards = ''
    for slug, data in rc.PAGES.items():
        dek = data.get('dek', '')
        if len(dek) > 150:
            dek = dek[:147].rstrip(' ,.;') + '\u2026'

        cards += (
            f'<a class="kn-guide-card" {CARD_MARKER} '
            f'href="/kitchen-notes/{esc(slug, quote=True)}/">'
            f'<span class="eyebrow">REFERENCE / CHARTS</span>'
            f'<span class="kn-series-badge">Reference</span>'
            f'<h3>{esc(data["title"])}</h3>'
            f'<p>{esc(dek)}</p>'
            f'<span class="text-link">Open the chart \u2197</span>'
            f'</a>'
        )
    return cards


def inject_cards(html, cards):
    """Append cards inside the existing grid.

    The grid contains only anchor elements, so matching to the first closing
    div is safe here.
    """
    if not cards or CARD_MARKER in html:
        return html, False

    match = re.search(r'(<div class="kn-card-grid">)(.*?)(</div>)', html, re.S)
    if not match:
        return html, False

    cut = match.end(2)
    return html[:cut] + cards + html[cut:], True


def fix_eyebrow(html):
    """"Three techniques" sat above a grid that is now much larger."""
    old = 'THREE TECHNIQUES TO KEEP'
    if old not in html:
        return html, False
    return html.replace(old, 'NOTES, TECHNIQUES AND CHARTS'), True


# ---------------------------------------------------------------------------
# robots.txt
# ---------------------------------------------------------------------------

def _sitemap_host():
    """Read an absolute host out of sitemap.xml, if one is present."""
    path = DIST / 'sitemap.xml'
    if not path.exists():
        return ''
    try:
        xml = path.read_text(encoding='utf-8')
    except Exception:
        return ''
    match = re.search(r'<loc>(https?://[^/<]+)', xml)
    return match.group(1) if match else ''


def fix_robots():
    """Indented directives are ignored, and Sitemap must be absolute.

    The generated file indented every line after the user-agent, which means
    crawlers read no directives at all. The sitemap line was also relative,
    which is invalid regardless of indentation. A relative sitemap is worse
    than none, so it is dropped until a real domain is configured.
    """
    path = DIST / 'robots.txt'
    if not path.exists():
        return False

    try:
        original = path.read_text(encoding='utf-8')
    except Exception:
        return False

    host = _sitemap_host()
    lines = []
    for line in original.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith('sitemap:'):
            target = line.split(':', 1)[1].strip()
            if target.startswith('/'):
                if not host:
                    continue
                line = f'Sitemap: {host}{target}'
        lines.append(line)

    rebuilt = '\n'.join(lines) + '\n'
    if rebuilt == original:
        return False

    path.write_text(rebuilt, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------
# Sitemap
# ---------------------------------------------------------------------------

def add_to_sitemap(slugs):
    """Append entries for any reference page missing from the sitemap.

    Clones the shell page's entry so host and lastmod format match whatever
    build.py emitted.
    """
    path = DIST / 'sitemap.xml'
    if not path.exists():
        return 0

    xml = path.read_text(encoding='utf-8')

    template = re.search(
        r'<url>\s*<loc>([^<]*' + re.escape(SHELL_SOURCE) + r'[^<]*)</loc>.*?</url>',
        xml, re.S,
    )
    if not template:
        return 0

    block = template.group(0)
    added = 0
    for slug in slugs:
        if f'/{slug}/' in xml:
            continue
        xml = xml.replace(block, block + block.replace(SHELL_SOURCE, slug), 1)
        added += 1

    if added:
        path.write_text(xml, encoding='utf-8')
    return added


# ---------------------------------------------------------------------------

def main():
    if not DIST.exists():
        print('postbuild_reference: dist/ not found, nothing to do')
        return 0

    print('postbuild_reference: starting')

    charts = load_charts()
    if charts:
        print(f'  {len(charts)} chart(s) discovered in charts/')

    rc = register(charts)
    if rc is None:
        print('postbuild_reference: done (nothing registered)')
        return 0

    for slug in charts:
        try:
            if write_page(rc, slug):
                print(f'  page written: /kitchen-notes/{slug}/')
        except Exception as exc:
            print(f'  warn: {slug} generation failed: {exc}')

    listing = DIST / 'kitchen-notes' / 'index.html'
    if listing.exists():
        try:
            html = listing.read_text(encoding='utf-8')
            original = html

            html, added = inject_cards(html, build_cards(rc))
            if added:
                print(f'  {len(rc.PAGES)} reference cards added to listing')

            html, fixed = fix_eyebrow(html)
            if fixed:
                print('  library eyebrow corrected')

            if html != original:
                listing.write_text(html, encoding='utf-8')
        except Exception as exc:
            print(f'  warn: listing update failed: {exc}')
    else:
        print('  warn: kitchen notes listing not found')

    try:
        if fix_robots():
            print('  robots.txt repaired')
    except Exception as exc:
        print(f'  warn: robots.txt failed: {exc}')

    try:
        count = add_to_sitemap(list(rc.PAGES.keys()))
        if count:
            print(f'  {count} sitemap entries added')
    except Exception as exc:
        print(f'  warn: sitemap update failed: {exc}')

    print('postbuild_reference: done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
