"""Reference pages: generation, discovery and crawl hygiene.

One pass, replacing postbuild_index.py and postbuild_herbs.py.

The problem this solves is not runtime, it is structure. Each new chart
had been arriving as its own script, because reference_content.py is 29KB
and appending a page meant rewriting the whole file. Four scripts in the
chain, and no single place to look up what generated what.

EXTRA_PAGES below is now the extension point. A new chart is a dict entry
in this file. Page generation, the listing card, the sitemap entry and the
Article schema all follow from that entry with no new script and no change
to vercel.json.

What this pass does, in order:

  1. Registers EXTRA_PAGES into reference_content.PAGES so the existing
     renderers can see them.
  2. Writes a page for each extra entry, cloning a live reference page as
     the HTML shell so header, footer, stylesheet links and font preloads
     stay identical with no markup duplicated here.
  3. Adds a card for every reference page to the kitchen notes grid, using
     the real kn-guide-card markup so the cards inherit existing styles.
  4. Corrects the library eyebrow, which claimed three techniques above a
     grid that has since grown to sixteen.
  5. Repairs robots.txt: generated directives were indented, which makes
     crawlers read none of them, and the sitemap line was relative when it
     must be absolute.
  6. Appends sitemap entries for any reference page missing from it.

Scope note: postbuild.py still owns the recipe-side transforms and the
first three reference pages. Both passes belong in build.py once the
structure stops moving.

Run locally with:
    python build.py && python postbuild.py && python postbuild_reference.py
"""
import json
import re
import sys
from html import escape as esc
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'

# Any live reference page works as the HTML shell. This one is generated by
# postbuild.py, so it exists before this pass runs.
SHELL_SOURCE = 'can-to-cup-conversions'

# Single marker for idempotency across all reference cards.
CARD_MARKER = 'data-reference-card'


# ---------------------------------------------------------------------------
# Extension point: pages defined here rather than in reference_content.py
# ---------------------------------------------------------------------------

EXTRA_PAGES = {}

EXTRA_PAGES['herb-substitution-chart'] = dict(
    title='Herb Substitution Chart',
    h1='Fresh to dried, and when not to bother.',
    dek='The three-to-one rule works for woody herbs. For parsley, cilantro '
        'and basil the honest answer is to reach for a different fresh herb '
        'instead.',
    description='Fresh to dried herb conversions with per-herb ratios, which '
                'herbs survive drying and which do not, and fresh '
                'alternatives for the ones that do not.',
    intro=[
        'Nearly every conversion chart gives the same rule: three parts fresh '
        'equals one part dried. It is a good rule, and it is also the reason '
        'a lot of dishes end up tasting of dust.',
        'The ratio accounts for water. Drying removes most of the moisture '
        'from a leaf, so the same flavour ends up in a third of the volume. '
        'What the ratio does not account for is aroma. Woody herbs hold their '
        'aromatic compounds when dried. Tender herbs lose most of theirs, '
        'somewhere between 60 and 80 per cent, and no amount of adjusting '
        'the quantity brings them back.',
        'So there are two questions, not one. How much dried do I use, and '
        'should I be using dried at all.',
    ],
    rule=dict(
        eyebrow='THE RULE, AND ITS LIMIT',
        items=[
            ('Woody herbs', '3 parts fresh to 1 part dried, by volume'),
            ('Tender herbs', 'Dried loses 60 to 80% of the aroma'),
            ('Timing', 'Dried goes in early, fresh goes in at the end'),
        ],
        example='A recipe calling for 1 tablespoon of fresh thyme becomes 1 '
                'teaspoon dried, added with the onions rather than at the '
                'end. A recipe calling for a handful of fresh basil does not '
                'convert at all.',
    ),
    tables=[dict(
        heading='Herbs that work dried',
        note='Woody, low-moisture herbs. These hold up in anything with '
             'liquid and twenty minutes or more of cooking. Note that the '
             'ratio is not 3:1 across the board \u2014 rosemary concentrates '
             'more than most, sage less.',
        caption='Fresh quantity on the left, dried equivalent on the right.',
        headers=['Herb', 'Fresh', 'Dried', 'Ratio', 'Best used in'],
        highlight=2,
        rows=[
            ['Rosemary', '1 tbsp chopped', '\u00be tsp', '4:1',
             'Roasts, braises, bread'],
            ['Thyme', '1 tbsp chopped', '1 tsp', '3:1',
             'Soups, beans, roasted vegetables'],
            ['Oregano', '1 tbsp chopped', '1 tsp', '3:1',
             'Tomato sauce, marinades'],
            ['Marjoram', '1 tbsp chopped', '1 tsp', '3:1',
             'Sauces, stuffing'],
            ['Sage', '1 tbsp chopped', '1\u00bd tsp', '2:1',
             'Squash, butter sauces, beans'],
            ['Tarragon', '1 tbsp chopped', '1 tsp', '3:1',
             'Cream sauces, chicken'],
            ['Dill, in cooked dishes', '1 tbsp chopped', '1 tsp', '3:1',
             'Braises and soups only'],
            ['Bay leaf', '1 fresh leaf', '2 dried leaves', 'By count',
             'Stocks, stews, beans'],
        ],
    ), dict(
        heading='Herbs that do not',
        note='Tender, high-moisture herbs. A ratio exists for each, and it '
             'is printed below, but the last column is the more useful '
             'answer. Substituting a different fresh herb almost always '
             'beats using the dried version of the right one.',
        caption='What to use instead when the fresh herb is not available.',
        headers=['Herb', 'Dried ratio', 'What dried does to it',
                 'Better substitute'],
        highlight=3,
        rows=[
            ['Basil', '3:1', 'Turns dull and faintly hay-like',
             'Fresh mint, or dried only in sauce cooked 30 min plus'],
            ['Parsley', '2:1', 'Loses nearly all its flavour',
             'Fresh cilantro, celery leaf or chervil'],
            ['Cilantro', '3:1', 'The citrus note disappears entirely',
             'Fresh parsley with a squeeze of lime'],
            ['Chives', 'Not worth it', 'Goes papery, tastes of nothing',
             'Green onion tops, thinly sliced'],
            ['Mint', '3:1', 'Works for tea, not for food',
             'Fresh basil, or fresh parsley for savoury dishes'],
            ['Dill, as a finish', '3:1', 'Loses the bright anise edge',
             'Fresh fennel fronds or tarragon'],
            ['Chervil', '3:1', 'Almost nothing survives',
             'Fresh parsley plus a little tarragon'],
        ],
    ), dict(
        heading='Aromatics',
        note='Garlic, onion and ginger follow their own conversions, and the '
             'powders are far more concentrated than the ratios for leaves '
             'would suggest. Granulated sits between fresh and powder.',
        caption='Fresh aromatics and their dried equivalents.',
        headers=['Fresh', 'Powder', 'Granulated', 'Note'],
        highlight=1,
        rows=[
            ['1 clove garlic, minced', '\u00bc tsp garlic powder',
             '\u00bd tsp', 'About 1 tsp minced fresh'],
            ['1 cup diced onion', '1 tbsp onion powder', '3 tbsp',
             'Powder browns quickly, add late'],
            ['1 tsp grated ginger', '\u00bc tsp ground ginger', '\u2014',
             'Ground is warmer, less bright'],
            ['1 tsp grated horseradish', '\u2014', '\u2014',
             'No dried equivalent worth using'],
            ['1 stalk lemongrass', '\u2014', '\u2014',
             'Use lemon zest plus a little ginger'],
        ],
    )],
    exceptions=[
        ('Ground is stronger than crumbled',
         ['Most charts assume dried leaves, crumbled between your fingers. '
          'Ground herbs have far more surface area and hit harder.',
          'Start at a third of the dried quantity when using ground, so a '
          'teaspoon of dried thyme becomes a third of a teaspoon of ground.']),
        ('Timing matters more than quantity',
         ['Dried herbs need heat and liquid to release what they have left. '
          'Add them with the aromatics at the start, or bloom them in oil '
          'for thirty seconds.',
          'Fresh herbs work the opposite way. Their aroma compounds are '
          'volatile, so anything added at the start is gone by the time the '
          'dish reaches the table. Stir them in off the heat.']),
        ('Dried basil has exactly one good use',
         ['In a tomato sauce simmered for half an hour or more, dried basil '
          'has time to rehydrate and integrate, and it works.',
          'Anywhere it stays raw or barely cooked \u2014 on a caprese, over '
          'finished pasta, in a dressing \u2014 there is no version of the '
          'ratio that rescues it.']),
        ('Frozen beats dried for tender herbs',
         ['Blend soft herbs with a little olive oil and freeze the paste in '
          'an ice cube tray. It keeps most of the aroma that drying '
          'destroys.',
          'It will not work as a garnish, since the texture goes, but for '
          'anything stirred into a dish it is much closer to fresh than the '
          'dried version.']),
    ],
    safety=None,
    sources=[
        ('Substituting Dried Herbs for Fresh', "America's Test Kitchen",
         'https://www.americastestkitchen.com/how_tos/9261-science-substituting-dried-herbs-for-fresh',
         'Basis for splitting the herbs into two groups, and for the advice '
         'not to substitute dried for tender herbs.'),
        ('How to Convert Fresh to Dried Herb Measurements', 'The Spruce Eats',
         'https://www.thespruceeats.com/convert-herb-measurements-1706231',
         'The 3:1 baseline and the sage and ginger conversions.'),
        ('Fresh to Dried Herb Converter', 'CookingCalcs',
         'https://cookingcalcs.com/tools/herb-converter.html',
         'Per-herb ratios that depart from 3:1, including rosemary at 4:1 '
         'and parsley at 2:1.'),
        ('Fresh Herb to Dried Herb Conversion Chart', 'Reluctant Gourmet',
         'https://reluctantgourmet.com/converting-fresh-herbs-to-dried-ratios/',
         'On bay leaves being counted rather than measured, and on ground '
         'versus crumbled.'),
        ('Fresh-to-Dried Herb Conversion Guide', 'Forks Over Knives',
         'https://www.forksoverknives.com/how-tos/fresh-to-dried-herb-conversion-guide-plus-garlic-onion-powder/',
         'Source for the garlic and onion powder equivalents.'),
    ],
    related=[
        ('/kitchen-notes/swapping-herbs/',
         'Swapping herbs without ruining the dish'),
        ('/kitchen-notes/simple-lemon-dressing/',
         'Make a simple lemon dressing'),
        ('/recipes/lemon-chickpea-salad/', 'Lemon chickpea salad'),
        ('/recipes/mediterranean-warm-green-lentils/',
         'Mediterranean warm green lentils'),
    ],
)


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

def register():
    """Merge EXTRA_PAGES into reference_content.PAGES.

    Returns the module, or None if it cannot be imported. Registering makes
    the existing body() and article_jsonld() renderers work on the extra
    pages without duplicating any rendering code here.
    """
    try:
        import reference_content as rc
    except Exception as exc:
        print(f'  skip: reference_content not importable ({exc})')
        return None

    for slug, data in EXTRA_PAGES.items():
        rc.PAGES[slug] = data
    return rc


# ---------------------------------------------------------------------------
# Page generation
# ---------------------------------------------------------------------------

def write_page(rc, slug):
    """Write one reference page, cloning a live page as the shell."""
    shell_path = DIST / 'kitchen-notes' / SHELL_SOURCE / 'index.html'
    if not shell_path.exists():
        print(f'  skip {slug}: shell page not found')
        return False

    data = rc.PAGES[slug]
    html = shell_path.read_text(encoding='utf-8')

    html = re.sub(
        r'<title>.*?</title>',
        f'<title>{esc(data["title"])} \u2014 Bored of Toast</title>',
        html, count=1, flags=re.S,
    )

    description = esc(data['description'], quote=True)
    title_attr = esc(data['title'], quote=True)

    html = re.sub(
        r'(<meta name="description" content=")[^"]*(")',
        lambda m: m.group(1) + description + m.group(2),
        html, count=1,
    )

    for prop in ('og:title', 'twitter:title'):
        html = re.sub(
            r'(<meta (?:property|name)="' + prop + r'" content=")[^"]*(")',
            lambda m: m.group(1) + title_attr + m.group(2),
            html, count=1,
        )

    for prop in ('og:description', 'twitter:description'):
        html = re.sub(
            r'(<meta (?:property|name)="' + prop + r'" content=")[^"]*(")',
            lambda m: m.group(1) + description + m.group(2),
            html, count=1,
        )

    # Canonical, og:url and any other self-references.
    html = html.replace(
        f'/kitchen-notes/{SHELL_SOURCE}/',
        f'/kitchen-notes/{slug}/',
    )

    body_html = rc.body(slug)
    html, count = re.subn(
        r'(<main[^>]*>)(.*?)(</main>)',
        lambda m: m.group(1) + body_html + m.group(3),
        html, count=1, flags=re.S,
    )
    if count == 0:
        print(f'  warn {slug}: <main> not found, page not written')
        return False

    schema = json.dumps(rc.article_jsonld(slug), ensure_ascii=False)
    html = re.sub(
        r'(<script type="application/ld\+json">)(.*?)(</script>)',
        lambda m: m.group(1) + schema + m.group(3),
        html, count=1, flags=re.S,
    )

    out_dir = DIST / 'kitchen-notes' / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / 'index.html').write_text(html, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------
# Listing cards
# ---------------------------------------------------------------------------

def build_cards(rc):
    """Cards for every reference page, in the existing card shape.

    reference_content defines its own index_cards(), but against class names
    that were never added to the stylesheet. Rendering against the real
    kn-guide-card markup means the cards inherit every existing style,
    including hover and focus states, with no CSS added.
    """
    cards = ''
    for slug, data in rc.PAGES.items():
        dek = data.get('dek', '')
        if len(dek) > 150:
            dek = dek[:147].rstrip(' ,.;') + '\u2026'

        cards += (
            f'<a class="kn-guide-card" {CARD_MARKER} '
            f'href="/kitchen-notes/{esc(slug, quote=True)}/">'
            f'<span class="eyebrow">REFERENCE / CHARTS</span>'
            f'<span class="kn-series-badge">Reference</span>'
            f'<h3>{esc(data["title"])}</h3>'
            f'<p>{esc(dek)}</p>'
            f'<span class="text-link">Open the chart \u2197</span>'
            f'</a>'
        )
    return cards


def inject_cards(html, cards):
    """Append cards inside the existing grid.

    The grid contains only anchor elements, so matching to the first closing
    div is safe here.
    """
    if not cards or CARD_MARKER in html:
        return html, False

    match = re.search(r'(<div class="kn-card-grid">)(.*?)(</div>)', html, re.S)
    if not match:
        return html, False

    cut = match.end(2)
    return html[:cut] + cards + html[cut:], True


def fix_eyebrow(html):
    """"Three techniques" sat above a grid that is now sixteen cards."""
    old = 'THREE TECHNIQUES TO KEEP'
    if old not in html:
        return html, False
    return html.replace(old, 'NOTES, TECHNIQUES AND CHARTS'), True


# ---------------------------------------------------------------------------
# robots.txt
# ---------------------------------------------------------------------------

def _sitemap_host():
    """Read an absolute host out of sitemap.xml, if one is present."""
    path = DIST / 'sitemap.xml'
    if not path.exists():
        return ''
    try:
        xml = path.read_text(encoding='utf-8')
    except Exception:
        return ''
    match = re.search(r'<loc>(https?://[^/<]+)', xml)
    return match.group(1) if match else ''


def fix_robots():
    """Indented directives are ignored, and Sitemap must be absolute.

    The generated file indented every line after the user-agent, which means
    crawlers read no directives at all. The sitemap line was also relative,
    which is invalid regardless of indentation. A relative sitemap is worse
    than none, so it is dropped until a real domain is configured.
    """
    path = DIST / 'robots.txt'
    if not path.exists():
        return False

    try:
        original = path.read_text(encoding='utf-8')
    except Exception:
        return False

    host = _sitemap_host()
    lines = []
    for line in original.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith('sitemap:'):
            target = line.split(':', 1)[1].strip()
            if target.startswith('/'):
                if not host:
                    continue
                line = f'Sitemap: {host}{target}'
        lines.append(line)

    rebuilt = '\n'.join(lines) + '\n'
    if rebuilt == original:
        return False

    path.write_text(rebuilt, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------
# Sitemap
# ---------------------------------------------------------------------------

def add_to_sitemap(slugs):
    """Append entries for any reference page missing from the sitemap.

    Clones the shell page's entry so host and lastmod format match whatever
    build.py emitted.
    """
    path = DIST / 'sitemap.xml'
    if not path.exists():
        return 0

    xml = path.read_text(encoding='utf-8')

    template = re.search(
        r'<url>\s*<loc>([^<]*' + re.escape(SHELL_SOURCE) + r'[^<]*)</loc>.*?</url>',
        xml, re.S,
    )
    if not template:
        return 0

    block = template.group(0)
    added = 0
    for slug in slugs:
        if f'/{slug}/' in xml:
            continue
        xml = xml.replace(block, block + block.replace(SHELL_SOURCE, slug), 1)
        added += 1

    if added:
        path.write_text(xml, encoding='utf-8')
    return added


# ---------------------------------------------------------------------------

def main():
    if not DIST.exists():
        print('postbuild_reference: dist/ not found, nothing to do')
        return 0

    print('postbuild_reference: starting')

    rc = register()
    if rc is None:
        print('postbuild_reference: done (nothing registered)')
        return 0

    for slug in EXTRA_PAGES:
        try:
            if write_page(rc, slug):
                print(f'  page written: /kitchen-notes/{slug}/')
        except Exception as exc:
            print(f'  warn: {slug} generation failed: {exc}')

    listing = DIST / 'kitchen-notes' / 'index.html'
    if listing.exists():
        try:
            html = listing.read_text(encoding='utf-8')
            original = html

            html, added = inject_cards(html, build_cards(rc))
            if added:
                print(f'  {len(rc.PAGES)} reference cards added to listing')

            html, fixed = fix_eyebrow(html)
            if fixed:
                print('  library eyebrow corrected')

            if html != original:
                listing.write_text(html, encoding='utf-8')
        except Exception as exc:
            print(f'  warn: listing update failed: {exc}')
    else:
        print('  warn: kitchen notes listing not found')

    try:
        if fix_robots():
            print('  robots.txt repaired')
    except Exception as exc:
        print(f'  warn: robots.txt failed: {exc}')

    try:
        count = add_to_sitemap(list(rc.PAGES.keys()))
        if count:
            print(f'  {count} sitemap entries added')
    except Exception as exc:
        print(f'  warn: sitemap update failed: {exc}')

    print('postbuild_reference: done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
