"""Discovery pass over dist/. Runs after postbuild.py.

The reference pages generated by postbuild.py were reachable only by typing
their URL. Nothing in the site's navigation pointed at them, which wastes the
internal linking that makes a content cluster work and hides the pages from
anyone browsing normally.

This pass handles reachability rather than presentation:

  1. Adds reference cards to the kitchen notes card grid, reusing the exact
     kn-guide-card markup the existing notes use, so the grid stays uniform.
  2. Corrects the library section eyebrow, which claimed three techniques
     above a grid of twelve.
  3. Repairs robots.txt: directives were indented, which invalidates them,
     and the sitemap reference was relative when it must be absolute.

Scope note: this is deliberately a second file. Folding it into postbuild.py
would mean rewriting 1200 lines for a 40-line change. Both passes belong in
build.py eventually; consolidate once the structure stops moving.

Run locally with:
    python build.py && python postbuild.py && python postbuild_index.py
"""
import re
import sys
from html import escape as esc
from pathlib import Path

ROOT = Path(__file__).parent
DIST = ROOT / 'dist'

# Marker so the pass is idempotent across repeated runs.
CARD_MARKER = 'data-reference-card'


# ---------------------------------------------------------------------------
# Reference cards in the kitchen notes listing
# ---------------------------------------------------------------------------

def reference_cards():
    """Build cards in the same shape as the existing kitchen note cards.

    reference_content defines its own index_cards(), but against class names
    that were never added to the stylesheet. Rendering here against the real
    kn-guide-card markup means the new cards inherit every existing style,
    including hover and focus states, with no CSS added.
    """
    try:
        import reference_content as rc
    except Exception as exc:
        print(f'  skip: reference_content not importable ({exc})')
        return ''

    cards = ''
    for slug, data in rc.PAGES.items():
        dek = data.get('dek', '')
        if len(dek) > 150:
            dek = dek[:147].rstrip(' ,.;') + '\u2026'

        cards += (
            f'<a class="kn-guide-card" {CARD_MARKER} '
            f'href="/kitchen-notes/{esc(slug, quote=True)}/">'
            f'<span class="eyebrow">REFERENCE / CHARTS</span>'
            f'<span class="kn-series-badge">Reference</span>'
            f'<h3>{esc(data["title"])}</h3>'
            f'<p>{esc(dek)}</p>'
            f'<span class="text-link">Open the chart \u2197</span>'
            f'</a>'
        )
    return cards


def inject_cards(html, cards):
    """Append the reference cards inside the existing card grid.

    The grid contains only anchor elements, so matching to the first closing
    div is safe here.
    """
    if not cards or CARD_MARKER in html:
        return html, False

    match = re.search(r'(<div class="kn-card-grid">)(.*?)(</div>)', html, re.S)
    if not match:
        return html, False

    cut = match.end(2)
    return html[:cut] + cards + html[cut:], True


def fix_library_eyebrow(html):
    """"Three techniques" sat above twelve cards, and now fifteen."""
    old = 'THREE TECHNIQUES TO KEEP'
    if old not in html:
        return html, False
    return html.replace(old, 'NOTES, TECHNIQUES AND CHARTS'), True


# ---------------------------------------------------------------------------
# robots.txt
# ---------------------------------------------------------------------------

def _sitemap_host():
    """Read an absolute host out of sitemap.xml, if one is present."""
    path = DIST / 'sitemap.xml'
    if not path.exists():
        return ''
    try:
        xml = path.read_text(encoding='utf-8')
    except Exception:
        return ''
    match = re.search(r'<loc>(https?://[^/<]+)', xml)
    return match.group(1) if match else ''


def fix_robots():
    """Indented directives are ignored, and Sitemap must be an absolute URL.

    The generated file indented every line after the user-agent, which means
    crawlers read no directives at all. The sitemap line was also relative,
    which is invalid regardless of indentation.
    """
    path = DIST / 'robots.txt'
    if not path.exists():
        return False

    try:
        original = path.read_text(encoding='utf-8')
    except Exception:
        return False

    host = _sitemap_host()
    lines = []
    for line in original.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.lower().startswith('sitemap:'):
            target = line.split(':', 1)[1].strip()
            if target.startswith('/') and host:
                line = f'Sitemap: {host}{target}'
            elif target.startswith('/') and not host:
                # A relative sitemap is worse than none: skip until a real
                # domain is configured.
                continue
        lines.append(line)

    rebuilt = '\n'.join(lines) + '\n'
    if rebuilt == original:
        return False

    path.write_text(rebuilt, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------

def main():
    if not DIST.exists():
        print('postbuild_index: dist/ not found, nothing to do')
        return 0

    print('postbuild_index: starting')

    cards = reference_cards()
    if cards:
        print('  reference cards built')

    listing = DIST / 'kitchen-notes' / 'index.html'
    if listing.exists():
        try:
            html = listing.read_text(encoding='utf-8')
            original = html

            html, added = inject_cards(html, cards)
            if added:
                print('  cards added to kitchen notes listing')

            html, fixed = fix_library_eyebrow(html)
            if fixed:
                print('  library eyebrow corrected')

            if html != original:
                listing.write_text(html, encoding='utf-8')
        except Exception as exc:
            print(f'  warn: listing update failed: {exc}')
    else:
        print('  warn: kitchen notes listing not found')

    try:
        if fix_robots():
            print('  robots.txt repaired')
    except Exception as exc:
        print(f'  warn: robots.txt failed: {exc}')

    print('postbuild_index: done')
    return 0


if __name__ == '__main__':
    sys.exit(main())
